config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :scores

  root to: 'games#pop_a_shot'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
class Score < ApplicationRecord
  default_scope { order(value: :desc) }

  def self.highscore
    first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def pop_a_shot
    @highscore = Score.highscore
    @score = Score.new
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def create
    @score = Score.create(score_params)
    redirect_to root_path
  end

  def index
    @scores = Score.all
  end

  private

  def score_params
    params.require(:score).permit(:value, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/pop_a_shot.html.erb
<div id="background">
  <%= link_to 'View Scores', scores_path, class: 'main-scores-link' %>
  <div id="timer">
  </div>

  <div id="scoreBoard">
    <span>Score: </span><span id="score">0</span>
  </div>

  <div id="court">
    <div id="ball"></div>
  </div>

  <div id="meter">
    <div class="passed zone"></div>
    <div class="long zone"></div>
    <div class="perfect zone"></div>
    <div class="short zone"></div>

    <div id="meter-fill"></div>
  </div>

  <div id="shotIndicator">Press the space bar to shoot</div>
  <div id="gameOverModal" class="hidden">
    <div id="gameOver">Game Over!</div>
    <div><span>Score: </span><span id="finalScore"></span></div>
    <div>Highscore: <%= @highscore&.value %> by <%= @highscore&.name %></div>
    <%= form_with(model: @score) do |f| %>
      <%= f.text_field :name, placeholder: 'Enter your name to save your score!', class: 'name-field' %>
      <%= f.hidden_field :value, id: 'scoreField' %>
      <%= f.submit 'Save Score', class: 'save-btn' %>
    <% end %>
    <%= link_to 'View all scores', scores_path, class: 'scores-btn' %>
    <button id="restart">Restart</button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PopAShot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scores/index.html.erb
<%= link_to 'Play Game', root_path %>

<% @scores.each do |score| %>
  <li><%= score.name %> : <%= score.value %></li>
<% end %>